### ISSUE TITLE
tars2csharp 工具

### ISSUE THREAD

**Issue by geffzhang** [TarsNET/Tars.NET#2]
- BNF词法/语法分析
- 代码生成
- Tars协议二进制编解码

只需编写ANTLR的语法文件，描述我们要解析的语言的语法，之后ANTLR就会自动生成能解析这种语言的解析器。也就是说，ANTLR是一种能写出程序的程序

基于ANTLR 对Tars 文件进行语法和词法分析，生成相应的代码，供客户端和服务端使用，并提供TARS协议的二进制流的编解码功能。
VS Code 插件  https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4

**Comment by geffzhang** [comment]
Irony项目不仅提供了开发库，而且还有一个图形化的语法解析器的测试工具，在写完自己的自定义语言的语法之后，还可以通过这个工具进行测试。Irony的一个特色就是运用了C#的运算符重载，使得语法定义借用了C#的编译功能（语法、类型检查等），简单直观，又不容易出错。http://www.cnblogs.com/daxnet/p/6953418.html

**Comment by geffzhang** [comment]
anltr更强大，nhibernate这样的框架也在使用anltr用于hql的解析，还有 https://github.com/lextm/restructuredtext-antlr ，irony更加csharp一些

**Comment by geffzhang** [comment]
https://github.com/TarsCloud/TarsJava/tree/master/tools/tars-maven-plugin/src/main/java/com/qq/tars/maven/parse  这个是java 用的anltr

**Comment by geffzhang** [comment]
https://tomassetti.me/getting-started-with-antlr-in-csharp/

**Comment by fs7744** [comment]
https://github.com/TarsNET/CLI 目前已实现简单的tars定义文件生成

**Comment by landonzeng** [comment]
目前.netcore 是否可以使用tars进行rpc通信呢？
