### ISSUE TITLE
能否把使用文档完善下？

### ISSUE THREAD

**Issue by liuzhenyulive** [TarsNET/Tars.NET#4]
能否把使用文档完善下啊？想好好了解一下这个项目并参与进来

**Comment by ElderJames** [comment]
现在开发计划是先对接Tars平台，再完善文档。如果想参与进来，可联系@geffzhang

**Comment by liuzhenyulive** [comment]
好的  是张队推荐我过来的  我先抽空把项目系统地了解一下
